services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  pgadmin-compose:
    image: dpage/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "and123@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "121212"
    ports:
      - "54321:80"
    depents_on:
      - postgres